name: CI

on:
  # runs on pushes to the main branch
  push:
    branches: [master]
  # also runs inside pull requests that target the main branch
  pull_request:
    branches: [master]

jobs:
  build:
    # uses a Ubuntu Docker image (like a virtual machine)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v18.11.0"
          cache: "npm"
      # install dependencies
      - run: npm ci
      # run ESLint & Prettier
      - run: npm run lint
      - run: npm run prettier
      # verify that there are no build errors
      - run: npm run build
      # run tests with Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start